server:
  port: 8081
## MySQL and JPA properties.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/99x?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
